//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supersonic.MSSQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Supersonic.MSSQL.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select p.name as Name
        ///, p.value as Value
        ///, t.name as ObjectName
        ///, cast(case
        ///	when t.type_desc = &apos;USER_TABLE&apos; then &apos;TABLE&apos;
        ///	when t.type_desc = &apos;SQL_STORED_PROCEDURE&apos; then &apos;PROCEDURE&apos;
        ///	else &apos;VIEW&apos;
        ///  end as varchar(20)) as ObjectType
        ///, s.name as ObjectSchema
        ///from sys.extended_properties p
        ///inner join sys.objects t on p.major_id = t.object_id
        ///inner join sys.schemas s on t.schema_id = s.schema_id
        ///where p.name like &apos;EF_%&apos;
        ///order by t.name
        ///.
        /// </summary>
        internal static string ExtendedProperties_InsertUpdate {
            get {
                return ResourceManager.GetString("ExtendedProperties_InsertUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///        FK.TABLE_NAME AS FK_Table,
        ///        FK.COLUMN_NAME AS FK_Column,
        ///        PK.TABLE_NAME AS PK_Table,
        ///        PK.COLUMN_NAME AS PK_Column,
        ///        FK.CONSTRAINT_NAME AS Constraint_Name,
        ///        FK.TABLE_SCHEMA AS fkSchema,
        ///        PK.TABLE_SCHEMA AS pkSchema,
        ///        PT.COLUMN_NAME AS primarykey
        ///FROM    INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS C
        ///        INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS FK
        ///            ON FK.CONSTRAINT_CATALOG = C.CONSTRAINT_CATALOG
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForeignKeySchema {
            get {
                return ResourceManager.GetString("ForeignKeySchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT		[Schema].[Name] [Schema], 
        ///			[Objects].[Name] [ObjectName], 
        ///			[Parameters].[name] [ParameterName],
        ///			[Parameters].[parameter_id] [ParameterId],
        ///			[Types].[Name] [TypeName],
        ///			[Parameters].[max_length] [MaxLength],
        ///			[Parameters].[default_value] [Default],
        ///			[Parameters].[is_output] [IsOutput],
        ///			(SELECT TOP(1) ep.value
        ///				FROM sys.fn_listextendedproperty(NULL, &apos;SCHEMA&apos;, [Schema].[Name], &apos;PROCEDURE&apos;, [Objects].[Name], NULL, NULL) AS ep 
        ///				WHERE ep.name = &apos;EF_MethodName&apos;) AS [Met [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoredProcedureSchema {
            get {
                return ResourceManager.GetString("StoredProcedureSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select			ef_schemas.name as [SchemaName],
        ///				ef_tables.name as [TableName],
        ///				ef_tables.type_desc as [TableType],
        ///				cast(ef_columns.column_id as int) as [Ordinal],
        ///				ef_columns.name as [ColumnName],
        ///				ef_columns.is_nullable as [IsNullable],
        ///				ef_types.name as [TypeName],
        ///				cast(isnull(ef_columns.max_length, 0) as int) as [MaxLength],
        ///				cast(isnull(ef_columns.precision, 0) as int) as [Precision],
        ///				object_definition(ef_columns.default_object_id) as [Default],
        ///				cast(isnull(ef_col [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableSchema {
            get {
                return ResourceManager.GetString("TableSchema", resourceCulture);
            }
        }
    }
}
